PCB_WIDTH = 55 + 4;
PCB_HEIGHT = 75 + 4;
PCB_DEPTH = 16 + 10;

WALL_THICKNESS = 5;

CASE_WIDTH = PCB_WIDTH + WALL_THICKNESS * 2;
CASE_HEIGHT = PCB_HEIGHT + WALL_THICKNESS * 2;

CASE_FRONT_DEPTH = PCB_DEPTH + WALL_THICKNESS;

SCREW_OFFSET = 4;

SUPPORT_DEPTH = 6;

USB_WIDTH = 13;
USB_DEPTH = 8;
